name: Create json
run-name: Creating the json files for github-pages ğŸš€
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  Create-Code-Set-Readme-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Parse files and extract json
        run: node tools/code-set-lookup/index.js

      - name: Deploy ğŸš€
        run: |
          git config user.name "github-actions"
          git config user.email "<>"
          git add .
          git commit -m "Automated JSON creation for github pages"
          git push
