name: Create json
run-name: Creating the json files for github-pages ğŸš€
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  Create-Code-Set-Readme-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Parse files and extract json
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Deploy ğŸš€
        run: |
          git config user.name "github-actions"
          git config user.email "<>"
          git commit -am "Automated JSON creation for github pages"
          git push
